      - name: Patch project linker settings
        shell: pwsh
        run: |
          $project = "TrainingPlugin/TrainingPlugin.vcxproj"
          $xml = Get-Content $project -Raw

          $target = '<AdditionalLibraryDirectories>K:\bakkesmod\BakkesMod-rewrite\x64\Release</AdditionalLibraryDirectories>'

          $replacement = @'
          <AdditionalDependencies>pluginsdk.lib;%(AdditionalDependencies)</AdditionalDependencies>
              <AdditionalLibraryDirectories>$(GITHUB_WORKSPACE)\sdk\lib;%(AdditionalLibraryDirectories)</AdditionalLibraryDirectories>
'@

          $xml = $xml.Replace(
            $target,
            $replacement.Trim()
          )

          $include = '<AdditionalIncludeDirectories>K:\bakkesmod\BakkesMod-rewrite\BakkesMod Rewrite</AdditionalIncludeDirectories>'
          $includeReplacement = '<AdditionalIncludeDirectories>$(GITHUB_WORKSPACE)\sdk\include;%(AdditionalIncludeDirectories)</AdditionalIncludeDirectories>'

          $xml = $xml.Replace($include, $includeReplacement)

          Set-Content $project $xml -Encoding UTF8

      - name: Build TrainingPlugin
        shell: pwsh
        run: |
          msbuild TrainingPlugin/TrainingPlugin.vcxproj `
            /p:Configuration=Release `
            /p:Platform=x64 `
            /p:PlatformToolset=v143 `
            /p:WindowsTargetPlatformVersion=10.0
